### ISSUE TITLE
mu-plugins/pantheon-* files and directories not reaching Pantheon site

### ISSUE THREAD

**Issue by johnwatkins0** [10up/pantheon-wp-deploy-action#12]
### Describe your question

https://github.com/10up/pantheon-wp-deploy-action/blob/eddc36ca93a76a01f782aafe510de3b43b90af5c/image/entrypoint.sh#L68-L72

I have a project whose repo is rooted in the wp-content directory. We are installing the [pantheon-systems/pantheon-mu-plugin](https://github.com/pantheon-systems/pantheon-mu-plugin) plugin with composer and have a file, `mu-plugins/pantheon-mu-plugin-loader.php` that loads the plugin entry file.

Because of the lines above, neither the plugin nor `mu-plugins/pantheon-mu-plugin-loader.php` are arriving on our environment. 

Should these lines be updated to allow the files in my repository to be committed to the Pantheon repository? It's possible there is something I'm missing, though; I'm open to suggestions as to how we can modify the approach within my repo to get the Pantheon mu plugin deploye.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by douz** [comment]
Hi @johnwatkins0 ,
Thank you for bringing this to our attention, I've removed `mu-plugins/pantheon*` from the `rsync` excludes so the Pantheon MU Plugins can be included in the payload.
